name:    gotyno-hs
version: 2.1.0
synopsis: A type definition compiler supporting multiple output languages.
description: Compiles type definitions into F#, TypeScript and Python, with validators, decoders and encoders.
license: BSD2
license-file: LICENSE.txt
category: Compiler
maintainer: Rickard Andersson <gonz@severnatazvezda.com>

dependencies:

- base >=4.9.1.0 && <5
- rio
- megaparsec
- pretty-show
- fsnotify
- text
- aeson
- brick
- vty
- qtility
- lens

extra-source-files:
- README.md
- CHANGELOG.md
- examples/*
- test/reference-output/*.ts
- test/reference-output/*.fs
- test/reference-output/*.py
- test/examples/*

default-extensions:
- ApplicativeDo
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DeriveLift
- DerivingStrategies
- DoAndIfThenElse
- DuplicateRecordFields
- EmptyDataDecls
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeSynonymInstances
- ViewPatterns
- TypeApplications

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -Werror=incomplete-patterns

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  gotyno-hs:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gotyno-hs
    - optparse-simple

# Test suite
tests:
  gotyno-hs-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - gotyno-hs
    - hspec >=2.0.0
