resolver: lts-18.28

packages:
- .

allow-different-user: true

ghc-options:
  "$locals": -fwrite-ide-info

extra-deps:
- github: quanterall/qtility
  commit: a077ce1a8275e0803acf71edc5817662f0f8a2ba
  subdirs:
  - qtility
  # nix-sha256: sha256-/g9d9gNRIxAGJAJjRKzAoNpf1hSE5XuCb2kPkGuH+iQ=

nix:
  enable: false
