name: Run tests and maybe build release

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - app/**
      - test/**
      - examples/**
      - package.yaml
      - stack.yaml
      - weeder.dhall
      - .github/workflows/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-global-
      - uses: actions/cache@v3
        name: Cache .stack-work
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('services/*/**/*.hs') }}
          restore-keys: |
            ${{ runner.os }}-stack-work-

      - name: Test
        run: stack build --test

      - name: Copy binary
        run: |
          ABSOLUTE_BINARY_PATH=`stack path --local-install-root`
          VERSION=`stack local 
          TARBALL_NAME="gotyno-hs-${{ runner.os }}-${{ github.sha }}.tar.gz"
          mv $ABSOLUTE_BINARY_PATH/bin/gotyno-hs ./gotyno-hs
          tar czf gotyno-hs-${{ runner.os }}-${{ github.sha }}.tar.gz gotyno-hs
          echo "Created tarball '$TARBALL_NAME'"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: gotyno-hs-${{ runner.os }}-${{ github.sha }}
          path: gotyno-hs-${{ runner.os }}-${{ github.sha }}.tar.gz

  upload-release:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: gotyno-hs-${{ runner.os }}-${{ github.sha }}
          path: ./
      
      - name: Rename tarball
        run: |
          mv gotyno-hs-${{ runner.os }}-${{ github.sha }}.tar.gz gotyno-hs-${{ runner.os }}-$GITHUB_REF_NAME.tar.gz
      
      - name: Create release
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: gotyno-hs-*.tar.gz
  
