name: Run tests and maybe build release

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - app/**
      - test/**
      - examples/**
      - package.yaml
      - stack.yaml
      - weeder.dhall
      - .github/workflows/test-and-release.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-global-
      - uses: actions/cache@v3
        name: Cache .stack-work
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('services/*/**/*.hs') }}
          restore-keys: |
            ${{ runner.os }}-stack-work-

      - name: Test
        run: stack build --test

      - name: Copy binary
        run: |
          ABSOLUTE_BINARY_PATH=`stack path --local-install-root`
          TARBALL_NAME="gotyno-hs-${{ runner.os }}-${{ github.sha }}.tar.gz"
          mv $ABSOLUTE_BINARY_PATH/bin/gotyno-hs ./gotyno-hs
          tar czf gotyno-hs-${{ runner.os }}-${{ github.sha }}.tar.gz gotyno-hs
          echo "Created tarball '$TARBALL_NAME' for ref '${{ github.ref }}'"
